language: objective-c
osx_image: xcode11.4
xcode_project: SampleApp.xcodeproj # path to your xcodeproj folder
xcode_scheme: SampleApp
jobs:
  include:
    - stage: build
      name: "Build"
      script: xcodebuild -workspace SampleApp.xcworkspace -scheme SampleApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - stage: test
      name: "Test"
      script: xcodebuild test -workspace SampleApp.xcworkspace -scheme SampleAppTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,OS=13.4.1,name=iPhone 11 Pro' ONLY_ACTIVE_ARCH=NO