language: objective-c
osx_image: xcode11.4
xcode_project: SampleApp.xcodeproj # path to your xcodeproj folder
xcode_scheme: SampleApp
jobs:
  include:
    - stage: build
      name: "Build"
      script: xcodebuild -workspace SampleApp.xcworkspace -scheme SampleApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO